-- select * from dummy limit 5;
-- insert into dummy (id, name) select generate_series(2,100000), repeat('A', 10);

-- select count(*) from dummy;

-- -- 6568 KB

-- select pg_size_pretty(pg_total_relation_size('dummy'))

-- select pg_relation_filepath('dummy');

-- delete from dummy where id<=50000;

-- vacuum full dummy;

-- show search_path;

-- create schema trading;

-- set search_path to trading;
-- create table accounts2(acc_id int, name varchar(100));

-- select 2147483648::bigint;

-- drop table customers;
-- create table customers(id bigint generated by default as identity primary key, name text not null);

-- insert into customers(id, name) values(2,'a');

-- select * from customers;

-- drop table prices;
-- create table prices (item text, price numeric(5,2)); -- 999.99

-- insert into prices values('i1', 1.5);

-- insert into prices values('i2', 1.999);
-- insert into prices values('i3', 1.994);
-- insert into prices values('i4', 231.99);
-- insert into prices values('i5', 22311.99);

-- select * from prices;


-- SELECT
--     10 + 3  AS addition,
--     10 - 3  AS subtraction,
--     10 * 3  AS multiplication,
--     10 / 3  AS division,
-- 	10 / 3.0  AS division,
--     10 % 3  AS modulo,
--     10 ^ 3  AS power,
-- 	POWER(2, 3)         AS power,
--     SQRT(25)            AS square_root,
--     ABS(-15)             AS absolute_value,
--     ROUND(12.567, 2)    AS rounded,
--     CEIL(12.3)          AS ceiling,
--     FLOOR(12.9)         AS floor;

-- select cast('42' as integer);

-- json and jsonb

-- select '{"a":1, "b":2, "a":10}'::json;

-- select '{"a":1, "b":2, "a":10}'::jsonb;

-- CREATE TABLE events (
--     id      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     payload jsonb NOT NULL
-- );

-- INSERT INTO events (payload) VALUES
-- ('{"type": "login",  "user": {"id": 1, "name": "Alice"}, "tags": ["web", "mobile"]}'),
-- ('{"type": "purchase", "user": {"id": 2, "name": "Bob"},  "amount": 49.99, "tags": ["web"]}'),
-- ('{"type": "logout", "user": {"id": 1, "name": "Alice"}}');


-- select jsonb_agg(to_jsonb(p)) from prices p;

-- select payload-> 'type' from events;
-- select payload->> 'type' from events;

-- select payload-> 'user' ->> 'name' from events;

-- select payload #>> '{user,name}' from events;

-- alter table events add column amount int;

-- update  events set amount = 120;

-- SELECT payload -> 'amount'  FROM events; 

-- SELECT (payload -> 'amount')::int + 50 FROM events; 
-- update events set payload = payload || '{"processed":false}' where id=1;
-- select * from events;

-- Set a nested value
-- UPDATE events
-- SET payload = jsonb_set(payload, '{user,name}', '"Alicia"')
-- WHERE id = 1;

-- -- Add to an array (append)
-- UPDATE events
-- SET payload = jsonb_set(payload, '{tags}', (payload -> 'tags') || '"beta"')
-- WHERE id = 1;

-- -- Remove a key
-- UPDATE events SET payload = payload - 'processed' WHERE id = 1;

-- -- Remove a nested key
-- UPDATE events SET payload = payload #- '{user,name}' WHERE id = 1;

-- select key, value from events, jsonb_each_text(payload) where id=1;

-- INSERT INTO events (payload) VALUES
-- ('{"type": "login",  "user": {"id": 10, "name": "Bob"}, "tags": ["web", "mobile"]}');
-- select payload ->> 'type' as type, count(*) from events group by 1;

-- create table employees(
-- 	id bigint generated always as identity,
-- 	email text not null,
-- 	salary numeric(10, 2) check(salary>0),
-- 	dept_id integer,
-- 	joined_at date default current_date,
-- 	created_at timestamp default current_timestamp,
-- 	constraint pk_employees primary key(id),
-- 	constraint uk_employees_email unique(email)
-- );
-- CREATE TABLE departments (
--     id   integer PRIMARY KEY,
--     name text NOT NULL
-- );

insert into departments values(1,'HR');

alter table employees add constraint fk_employees_departments foreign key(dept_id) references departments(id);

-- insert into employees(email, salary, dept_id) values('a@a.com', 86876,1);

-- insert into employees(email, salary, joined_at, dept_id) values('b@a.com', 86876,'2026-05-10',1);

select * from employees;